FROM ubuntu:20.04

USER root

ENV HOME=/root \
    DEBIAN_FRONTEND=noninteractive \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=C.UTF-8 \
    DISPLAY=:0

# 安装必要的软件包和工具
RUN apt-get update && apt-get install -y \
    curl \
    git \
    build-essential \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# 升级 pip
RUN python3 -m pip install --upgrade pip

# 安装所需的编译器、解释器等工具
# 这里假设您的install.sh文件已在本地，并位于与Dockerfile相同的目录中
COPY install.sh /tmp/
RUN chmod +x /tmp/install.sh
RUN bash /tmp/install.sh

# 安装Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs

# 安装VS Code
RUN curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
RUN install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" | tee /etc/apt/sources.list.d/vscode.list
RUN apt-get update && apt-get install -y code

RUN apt-get install -y python3.8

# 安装Python库和 Jupyter 内核
RUN pip install numpy matplotlib tqdm openpyxl gym torch ipykernel scipy

# 安装 VS Code 扩展
RUN code-server --install-extension ms-python.python
RUN code-server --install-extension ms-toolsai.jupyter

# 设置工作目录
WORKDIR /workspace

# 将当前文件夹中的 The_Coding 文件夹复制到容器的工作目录
COPY ./Code-of-RL-Beginning /workspace/Code-of-RL-Beginning
# 暴露code-server的默认端口
EXPOSE 8080

# 启动code-server
CMD ["code-server", "--bind-addr", "0.0.0.0:8080", "."](